# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 22:49
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20160922_1355'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_topic',
            field=models.CharField(choices=[('PY', 'Python'), ('ML', 'Machine Learning'), ('OT', 'Others')], default=datetime.datetime(2016, 11, 9, 22, 49, 52, 722157, tzinfo=utc), max_length=1),
            preserve_default=False,
        ),
    ]
