# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-09 23:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_post_topic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_topic',
            field=models.CharField(choices=[('PY', 'Python'), ('ML', 'Machine Learning'), ('OT', 'Others')], max_length=2),
        ),
    ]
