# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-11-30 23:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_auto_20161111_0254'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_classif',
            field=models.CharField(choices=[('AD', 'Adulto'), ('PU', 'Apto Para Todos')], default='PU', max_length=2),
            preserve_default=False,
        ),
    ]
